apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  - mysql/secret.yaml
  - mysql/service.yaml
  - mysql/statefulset.yaml

  - redis/secret.yaml
  - redis/service.yaml
  - redis/statefulset.yaml

  - backend/deployment.yaml
  - backend/service.yaml
  - backend/ingress.yaml